spring.application.name=api-gateway
server.port=9000

#Keycloak
keycloak.auth.jwk-set-uri= http://localhost:8091/realms/energy-tracking/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt,issuer-uri = http://localhost:8091/realms/energy-tracking